version: '3'
services:
  strapi:
    build: .
    container_name: strapi-app
    ports:
      - "1337:1337"
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: strapi
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi123
      NODE_ENV: production
    depends_on:
      - db

volumes:
  pgdata: